apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: prod
type: Opaque
data:
  STRIPE_SECRET_KEY: "c2tfdGVzdF81MUQ2dktBUnRCSUtOaFFoQlZlb2FoU0RmcmdEV2E4N3F1bWZSaGUwZGMwOHphVFJmdUd4ck9tS1p6S1pISU5NRlJWV2ZZbGRSWGF5TXh6TEE4MVEzcWNrcjAwUnhFVGJkU2c="
  STRIPE_PUBLISHABLE_KEY: "cGtfdGVzdF81MUQ2dktBUnRCSUtOaFFCUk1LTW10ekYzclNVdGVRVU1teVQ3YnZNUHZob3dUd0VObUVDS3I4aXFxM1JmNVI3cnBqZU9vaHdJbmkyVFZ2aFdvcmVoSTg0ZTAwOGVhOHFzQ0M="
  SERVER_ADDRESS: "aHR0cDovL2xvY2FsaG9zdDo1MDg1"